#!/bin/bash
tmpdir=$(mktemp -d /tmp/nbrel.XXXXXX)
cp -rdp notebooks ${tmpdir}/
cp -rdp datasets ${tmpdir}/notebooks/
tar -C ${tmpdir} -zcf notebooks.tgz --exclude=".ipynb_checkpoints"  notebooks
rm -rf ${tmpdir}
