#!/bin/bash
tmpdir=$(mktemp -d /tmp/nbrel.XXXXXX)
mkdir -p ${tmpdir}/notebooks
cp -rdp notebooks/lecture* ${tmpdir}/notebooks/
cp -rdp datasets ${tmpdir}/notebooks/
tar -C ${tmpdir} -zcf notebooks.tgz --exclude=".ipynb_checkpoints"  notebooks
rm -rf ${tmpdir}
